### ISSUE TITLE
Unable to Start D2R?

### ISSUE THREAD

**Issue by SalmanTKhan** [mendite/D2RStart#1]
![image](https://user-images.githubusercontent.com/3139467/211646809-209145f8-ef01-40a6-9d46-863e6b339671.png)
Hi,
I compiled the project, and when I run the project, I get the error listed above.

**Comment by mendite** [comment]
You have to download Handle from Microsoft and extract it in executing Directory.

[https://learn.microsoft.com/en-us/sysinternals/downloads/handle](url)

**Comment by mendite** [comment]
I added hint window at startup with download link and instructions.
