### ISSUE TITLE
Still unable to start D2R

### ISSUE THREAD

**Issue by SalmanTKhan** [mendite/D2RStart#2]
In the function GetD2RExeInfo(), process ExitCode returns 1. Any idea what can cause it? The exception message is empty too. Any other additional steps for the setup? I've tried running it without visual studio and as admin.
`
if (process.ExitCode != 0)
                throw new Exception(stdError);
`

**Comment by mendite** [comment]
Can't reproduce it. I have two different installation directories for "Diablo 2 Resurrected" (you can add more if you want!) and i copied handle64.exe to executing path of application. Additional you have to configure your Blizzard-Launcher - documentation you can finde at [https://us.forums.blizzard.com/en/d2r/t/how-to-multiple-d2r-instances-requires-two-accounts/60546](url). Next time i want to write a documentation. An idea - do you run it at a 32bit machine?

**Comment by mendite** [comment]
No response
